# Generated by Django 4.0.2 on 2022-02-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeferTorah',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('physical_location', models.TextField(choices=[('Main', 'Main Shul'), ('SY', 'Shaar Yaakov'), ('Horowitz', 'Horowitz'), ('YABM', 'Yona Avraham')])),
            ],
        ),
    ]
