# Generated by Django 4.0.2 on 2022-02-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='current_ownership',
            field=models.CharField(choices=[('Loan', 'Loan'), ('Owned', 'Owned')], default='Loan', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='donated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='donator',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='last_checked',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='location_in_text',
            field=models.CharField(default='פרשת השבוע', max_length=250),
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sefertorah',
            name='quality',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, "Don't Use")], default=4, max_length=10),
        ),
        migrations.AlterField(
            model_name='sefertorah',
            name='physical_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.physicallocation'),
        ),
    ]
