# Generated by Django 4.0.2 on 2022-02-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_physicallocation_name_alter_sefertorah_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sefertorah',
            options={'verbose_name_plural': 'Sifrei Torah'},
        ),
    ]
